// teams
export const REQUEST_TEAMS = 'REQUEST_TEAMS';
export const REQUEST_TEAMS_SUCCEEDED = 'REQUEST_TEAMS_SUCCEEDED';
export const REQUEST_TEAMS_FAILED = 'REQUEST_TEAMS_FAILED';

// fixtures
export const REQUEST_FIXTURES = 'REQUEST_FIXTURES';
export const REQUEST_FIXTURES_SUCCEEDED = 'REQUEST_FIXTURES_SUCCEEDED';
export const REQUEST_FIXTURES_FAILED = 'REQUEST_FIXTURES_FAILED';
export const UPDATE_FIXTURES = 'UPDATE_FIXTURES';
